let tempData = [
  {
    id: "6FmFeux5xH",
    handle: "pandemic",
    url: "https://www.boardgameatlas.com/game/6FmFeux5xH/pandemic",
    name: "Pandemic",
    price: "35.99",
    price_ca: "41.95",
    price_uk: "24.98",
    price_au: "44.99",
    msrp: 44.99,
    msrps: [
      {
        country: "US",
        price: 44.99,
      },
      {
        country: "CA",
        price: 0,
      },
      {
        country: "UK",
        price: 39.99,
      },
    ],
    discount: "0.20",
    year_published: 2008,
    min_players: 2,
    max_players: 4,
    min_playtime: 45,
    max_playtime: 60,
    min_age: 8,
    description:
      "<p>After five years of Pandemic, hundreds of thousands of players have contracted the virus! To celebrate this milestone, Pandemic has been completely re-designed. With new artwork by Chris Quilliams (Clash of Cultures, Merchants &amp; Marauders), Pandemic will now have a more modern look, inside and outside the box. With two new characters (the Contingency Planner and the Quarantine Specialist) face the game in ways you never thought possible as brand-new, virulent challenges await you!</p>\r\n<p>In <em><strong>Pandemic</strong></em>, several virulent diseases have broken out simultaneously all over the world! The players are disease-fighting specialists whose mission is to treat disease hotspots while researching cures for each of four plagues before they get out of hand.</p>\r\n<p>The game board depicts several major population centers on Earth. On each turn, a player can use up to four actions to travel between cities, treat infected populaces, discover a cure, or build a research station. A deck of cards provides the players with these abilities, but sprinkled throughout this deck are <em>Epidemic!</em> cards that accelerate and intensify the diseases' activity. A second, separate deck of cards controls the &quot;normal&quot; spread of the infections.</p>\r\n<p>Taking a unique role within the team, players must plan their strategy to mesh with their specialists' strengths in order to conquer the diseases. For example, the Operations Expert can build research stations which are needed to find cures for the diseases and which allow for greater mobility between cities; the Scientist needs only four cards of a particular disease to cure it instead of the normal five—but the diseases are spreading quickly and time is running out. If one or more diseases spreads beyond recovery or if too much time elapses, the players all lose. If they cure the four diseases, they all win!</p>\r\n<p>The 2013 edition of <em>Pandemic</em> includes two new characters—the Contingency Planner and the Quarantine Specialist—not available in earlier editions of the game.</p>\r\n<h4>Artists:</h4>\r\n<p>Joshua Cappel (graphics and illustration)</p>\r\n<p>Régis Moulun (cover painting)</p>\r\n<p>Chris Quilliams (2013 edition)<br /><br /><br /></p>",
    commentary: "",
    faq: "",
    thumb_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254186140-51iNoyxoamL.jpg",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254186140-51iNoyxoamL.jpg",
    matches_specs: null,
    specs: [],
    mechanics: [
      {
        id: "oeg6wN9Eoc",
        url: "https://www.boardgameatlas.com/mechanic/oeg6wN9Eoc/undefined",
      },
      {
        id: "hwyCo1W0hi",
        url: "https://www.boardgameatlas.com/mechanic/hwyCo1W0hi/undefined",
      },
      {
        id: "9mNukNBxfZ",
        url: "https://www.boardgameatlas.com/mechanic/9mNukNBxfZ/undefined",
      },
      {
        id: "WPytek5P8l",
        url: "https://www.boardgameatlas.com/mechanic/WPytek5P8l/undefined",
      },
      {
        id: "MEAoOygZsA",
        url: "https://www.boardgameatlas.com/mechanic/MEAoOygZsA/undefined",
      },
      {
        id: "lA3KUtVFCy",
        url: "https://www.boardgameatlas.com/mechanic/lA3KUtVFCy/undefined",
      },
      {
        id: "AVY6EvSQTP",
        url: "https://www.boardgameatlas.com/mechanic/AVY6EvSQTP/undefined",
      },
      {
        id: "XM2FYZmBHH",
        url: "https://www.boardgameatlas.com/mechanic/XM2FYZmBHH/undefined",
      },
    ],
    categories: [
      {
        id: "AeWXMxbm91",
        url: "https://www.boardgameatlas.com/category/AeWXMxbm91/undefined",
      },
    ],
    publishers: [
      {
        id: "UPqP0MXLqj",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/UPqP0MXLqj/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "vJkLBDgn1j",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/vJkLBDgn1j/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "b33BrKkCsN",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/b33BrKkCsN/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "UMssR9EGlp",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/UMssR9EGlp/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    designers: [
      {
        id: "DKHpfErJB9",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/designer/DKHpfErJB9/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    primary_publisher: {
      id: "UPqP0MXLqj",
      name: "Z-Man Games, Inc.",
      url: "https://www.boardgameatlas.com/publisher/UPqP0MXLqj/zman-games-inc",
    },
    primary_designer: {
      id: "DKHpfErJB9",
      name: "Matt Leacock",
      url: "https://www.boardgameatlas.com/designer/DKHpfErJB9/matt-leacock",
    },
    developers: [],
    related_to: [],
    artists: ["Joshua Cappel", "Régis Moulun", "Chris Quilliams"],
    names: [],
    rules_url:
      "https://images-cdn.zmangames.com/us-east-1/filer_public/25/12/251252dd-1338-4f78-b90d-afe073c72363/zm7101_pandemic_rules.pdf",
    amazon_rank: 316,
    cs_rating: 4.5,
    official_url:
      "https://www.zmangames.com/en/products/pandemic?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
    comment_count: 1,
    num_user_ratings: 845,
    average_user_rating: 3.6282367181491257,
    weight_amount: 2.3,
    weight_units: "lbs",
    size_height: 12,
    size_depth: 1.7,
    size_units: "inches ",
    historical_low_prices: [
      {
        country: "AU",
        date: "2021-03-10T19:05:18.134Z",
        price: 44.99,
        isLow: true,
      },
      {
        country: "CA",
        date: "2021-03-31T16:19:54.354Z",
        price: 41.95,
        isLow: false,
      },
      {
        country: "US",
        date: "2021-04-29T15:19:21.699Z",
        price: 35.99,
        isLow: false,
      },
      {
        country: "UK",
        date: "2021-04-30T04:59:09.328Z",
        price: 24.98,
        isLow: true,
      },
    ],
    active: true,
    bgg_id: 30549,
    num_user_complexity_votes: 5,
    average_learning_complexity: 2.4,
    average_strategy_complexity: 2,
    visits: 2655,
    lists: 1703,
    mentions: 98,
    links: 20,
    plays: 4625,
    rank: 7,
    type: "game",
    sku: "ZMG7102",
    upc: "841333106874",
    num_distributors: 1,
    trending_rank: 0,
    listing_clicks: 13,
    is_historical_low: false,
    msrp_text: "$44.99",
    price_text: "$35.99",
    tags: [
      "Pandemic: 10th Anniversary Edition",
      "EPIZOotic",
      "Pandemia",
      "Pandemia 10 Aniversario",
      "Pandemia: Una Nuova Sfida",
      "Pandemic, 10 Jahre Jubiläumsedition",
      "Pandemic, Edición 10º Aniversario",
      "Pandemic: Edition 10ème anniversaire",
      "Pandemic: Una nuova sfida",
      "Pandémie",
      "Pandemie",
      "Πανδημία",
      "Пандемия",
      "เกมโรคระบาด",
      "パンデミック",
      "パンデミック：新たなる試練",
      "瘟疫危機 (瘟疫危机)",
      "팬데믹",
      "Pandemic",
      "Pandemic Anniversary Edition",
      "Pandemic 2013",
      "Pandemic Edition Collection Base Game w On the Brink Expansion",
      "Pandemic Edition w Wooden Pieces",
      "Pandemic Edition Collection Base Game On the Brink Expansion",
      "Pandemic Edition Collection Base Game 2 Expansions",
      "Pandemic board game",
    ],
    images: {
      thumb:
        "https://d2k4q26owzy373.cloudfront.net/40x40/games/uploaded/1559254186140-51iNoyxoamL.jpg",
      small:
        "https://d2k4q26owzy373.cloudfront.net/150x150/games/uploaded/1559254186140-51iNoyxoamL.jpg",
      medium:
        "https://d2k4q26owzy373.cloudfront.net/350x350/games/uploaded/1559254186140-51iNoyxoamL.jpg",
      large:
        "https://d2k4q26owzy373.cloudfront.net/700x700/games/uploaded/1559254186140-51iNoyxoamL.jpg",
      original:
        "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254186140-51iNoyxoamL.jpg",
    },
    description_preview:
      " After five years of Pandemic, hundreds of thousands of players have contracted the virus! To celebrate this milestone, Pandemic has been completely re-designed. With new artwork by Chris Quilliams (Clash of Cultures, Merchants & Marauders), Pandemic will now have a more modern look, inside and outside the box. With two new characters (the Contingency Planner and the Quarantine Specialist) face the game in ways you never thought possible as brand-new, virulent challenges await you! \r\n In   Pandemic  , several virulent diseases have broken out simultaneously all over the world! The players are disease-fighting specialists whose mission is to treat disease hotspots while researching cures for each of four plagues before they get out of hand. \r\n The game board depicts several major population centers on Earth. On each turn, a player can use up to four actions to travel between cities, treat infected populaces, discover a cure, or build a research station. A deck of cards provides the players with these abilities, but sprinkled throughout this deck are  Epidemic!  cards that accelerate and intensify the diseases' activity. A second, separate deck of cards controls the \"normal\" spread of the infections. \r\n Taking a unique role within the team, players must plan their strategy to mesh with their specialists' strengths in order to conquer the diseases. For example, the Operations Expert can build research stations which are needed to find cures for the diseases and which allow for greater mobility between cities; the Scientist needs only four cards of a particular disease to cure it instead of the normal five—but the diseases are spreading quickly and time is running out. If one or more diseases spreads beyond recovery or if too much time elapses, the players all lose. If they cure the four diseases, they all win! \r\n The 2013 edition of  Pandemic  includes two new characters—the Contingency Planner and the Quarantine Specialist—not available in earlier editions of the game. \r\n Artists: \r\n Joshua Cappel (graphics and illustration) \r\n Régis Moulun (cover painting) \r\n Chris Quilliams (2013 edition)    ",
  },
  {
    id: "oGVgRSAKwX",
    handle: "carcassonne",
    url: "https://www.boardgameatlas.com/game/oGVgRSAKwX/carcassonne",
    name: "Carcassonne",
    price: "28.79",
    price_ca: "33.95",
    price_uk: "27.99",
    price_au: "44.99",
    msrp: 39.99,
    msrps: [
      {
        country: "UK",
        price: 0,
      },
      {
        country: "CA",
        price: 38.24,
      },
      {
        country: "US",
        price: 39.99,
      },
    ],
    discount: "0.28",
    year_published: 2000,
    min_players: 2,
    max_players: 5,
    min_playtime: 30,
    max_playtime: 45,
    min_age: 7,
    description:
      "<p>Each game of <em>Carcassonne</em> reveals a unique environment as tiles form a landscape of cities, roads, fields, and monasteries. Claim these features with your followers to win the game.</p>\r\n<p><em>Carcassonne</em> is a tile placement game where players collectively construct the area around the medieval French city of Carcassonne while competing to place followers on various features and score the most points.</p>\r\n<p>First published in 2000, the game's accessible yet deep design has attracted a wide fan base and led to the development of numerous expansions (eg Rivers) and standalone titles in the <em>Carcassonne</em> line.</p>",
    commentary: "",
    faq: "",
    thumb_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254282618-61HduAZGE7L.jpg",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254282618-61HduAZGE7L.jpg",
    matches_specs: null,
    specs: [],
    mechanics: [
      {
        id: "9NBcz45nN7",
        url: "https://www.boardgameatlas.com/mechanic/9NBcz45nN7/undefined",
      },
      {
        id: "8PN2HE86wg",
        url: "https://www.boardgameatlas.com/mechanic/8PN2HE86wg/undefined",
      },
    ],
    categories: [
      {
        id: "ODWOjWAJj3",
        url: "https://www.boardgameatlas.com/category/ODWOjWAJj3/undefined",
      },
      {
        id: "7rV11PKqME",
        url: "https://www.boardgameatlas.com/category/7rV11PKqME/undefined",
      },
      {
        id: "QAYkTHK1Dd",
        url: "https://www.boardgameatlas.com/category/QAYkTHK1Dd/undefined",
      },
    ],
    publishers: [
      {
        id: "M0j3iwMtqL",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/M0j3iwMtqL/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "r2R8bUHIRD",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/r2R8bUHIRD/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "ja1W0hp62r",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/ja1W0hp62r/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "P9ZfBj0BBq",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/P9ZfBj0BBq/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "1TaoBxZ3GH",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/1TaoBxZ3GH/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "UMssR9EGlp",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/UMssR9EGlp/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "J8pMyONAQy",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/J8pMyONAQy/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "32liHCLQDl",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/32liHCLQDl/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "BrfTva4mEF",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/BrfTva4mEF/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "UPqP0MXLqj",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/UPqP0MXLqj/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    designers: [
      {
        id: "ILPwtQUfMU",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/designer/ILPwtQUfMU/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    primary_publisher: {
      id: "M0j3iwMtqL",
      name: "Hans im Glück",
      url: "https://www.boardgameatlas.com/publisher/M0j3iwMtqL/hans-im-glck",
    },
    primary_designer: {
      id: "ILPwtQUfMU",
      name: "Klaus-Jurgen Wrede",
      url:
        "https://www.boardgameatlas.com/designer/ILPwtQUfMU/klausjurgen-wrede",
    },
    developers: [],
    related_to: [],
    artists: [
      "Doris Matthäus",
      "Anne Pätzke",
      "Chris Quilliams",
      "Klaus-Jürgen Wrede",
    ],
    names: [],
    rules_url:
      "https://images-cdn.zmangames.com/us-east-1/filer_public/d5/20/d5208d61-8583-478b-a06d-b49fc9cd7aaa/zm7810_carcassonne_rules.pdf",
    amazon_rank: 901,
    official_url:
      "https://www.zmangames.com/en/products/carcassonne/?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
    comment_count: 2,
    num_user_ratings: 759,
    average_user_rating: 3.567852437417658,
    weight_amount: 1.55,
    weight_units: "lbs",
    size_height: 10.8,
    size_depth: 2.6,
    size_units: "inches",
    historical_low_prices: [
      {
        country: "UK",
        date: "2021-02-04T17:47:08.750Z",
        price: 27.99,
        isLow: false,
      },
      {
        country: "AU",
        date: "2021-02-16T00:44:22.966Z",
        price: 44.99,
        isLow: false,
      },
      {
        country: "CA",
        date: "2021-02-17T00:53:36.936Z",
        price: 33.95,
        isLow: false,
      },
      {
        country: "US",
        date: "2021-04-30T10:55:22.899Z",
        price: 28.79,
        isLow: false,
      },
    ],
    active: true,
    bgg_id: 822,
    num_user_complexity_votes: 13,
    average_learning_complexity: 1.4615384615384615,
    average_strategy_complexity: 2.8461538461538463,
    visits: 3080,
    lists: 1520,
    mentions: 154,
    links: 20,
    plays: 6879,
    rank: 14,
    type: "game",
    sku: "ZMG7810",
    upc: "681706781006",
    num_distributors: 1,
    trending_rank: 0,
    listing_clicks: 0,
    is_historical_low: false,
    msrp_text: "$39.99",
    price_text: "$28.79",
    tags: [
      "Carcassonne Jubilee Edition",
      "Carcassonne: Plus",
      "Domínio de Carcassonne",
      "Τα Κάστρα του Μυστρά",
      "Каркасон",
      "Каркассон",
      "Средневековье",
      "קרקסון",
      "คาร์คาซอนน์",
      "カルカソンヌ",
      "カルカソンヌＪ",
      "卡卡頌",
      "카르카손",
      "Carcassonne",
      "Carcassonne w River Expansion 2000 Edition",
      "Carcassonne 2000 Edition",
      "Carcassonne - Dent & Ding",
      "Carcassonne Collection Base Game 2 Expansions",
      "Carcassonne Collection 6 Base Game 3 Expansions",
      "Carcassonne Collection 7 Base Game 4 Expansions",
      "Carcassonne Collection 8 Base Game 3 Expansions",
      "Carcassonne Collection Base Game 5 Expansions",
      "Carcassonne Base 2 0 Nouvelle version",
      "Carcassonne 2 0 New Edition",
      "Carcassonne Game (New Edition)_ for 2 to 5 Players _ Includes River Expansion & The Abbot Expansion _ Bonus 2 Gold Drawstring Storage Bags by Z-Man Games",
      "Carcassonne Classic",
    ],
    images: {
      thumb:
        "https://d2k4q26owzy373.cloudfront.net/40x40/games/uploaded/1559254282618-61HduAZGE7L.jpg",
      small:
        "https://d2k4q26owzy373.cloudfront.net/150x150/games/uploaded/1559254282618-61HduAZGE7L.jpg",
      medium:
        "https://d2k4q26owzy373.cloudfront.net/350x350/games/uploaded/1559254282618-61HduAZGE7L.jpg",
      large:
        "https://d2k4q26owzy373.cloudfront.net/700x700/games/uploaded/1559254282618-61HduAZGE7L.jpg",
      original:
        "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254282618-61HduAZGE7L.jpg",
    },
    description_preview:
      " Each game of  Carcassonne  reveals a unique environment as tiles form a landscape of cities, roads, fields, and monasteries. Claim these features with your followers to win the game. \r\n  Carcassonne  is a tile placement game where players collectively construct the area around the medieval French city of Carcassonne while competing to place followers on various features and score the most points. \r\n First published in 2000, the game's accessible yet deep design has attracted a wide fan base and led to the development of numerous expansions (eg Rivers) and standalone titles in the  Carcassonne  line. ",
  },
  {
    id: "OIXt3DmJU0",
    handle: "catan",
    url: "https://www.boardgameatlas.com/game/OIXt3DmJU0/catan",
    name: "Catan",
    price: "44.10",
    price_ca: "44.95",
    price_uk: "28.98",
    price_au: "59.95",
    msrp: 55,
    msrps: [
      {
        country: "CA",
        price: 0,
      },
      {
        country: "UK",
        price: 0,
      },
      {
        country: "US",
        price: 55,
      },
    ],
    discount: "0.20",
    year_published: 1995,
    min_players: 3,
    max_players: 4,
    min_playtime: 45,
    max_playtime: 90,
    min_age: 10,
    description:
      "<p>The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan? Barter trade dominates the scene. Some resources you have in abundance, other resources are scarce. Ore for wool, brick for lumber - you trade according to what is needed for your current building projects. Proceed strategically! If you found your settlements in the right places and skillfully trade your resources, then the odds will be in your favor. But your opponents are smart too.</p>\r\n<p>To begin the game, we build the game board using hexagonal terrain tiles. Catan is born - a beautiful island with mountains, pastures, hills, fields, and forests, surrounded by the sea.</p>\r\n<p>Each of us places two small houses on spaces where three terrain hexes meet. They are our starting settlements.</p>\r\n<p>And so it begins. I roll two dice. An “11”! Each terrain hex is marked with a die roll number. Each player who owns a settlement adjacent to a terrain hex marked with the number rolled receives a resource produced by this hex. Hills produce brick, forests produce lumber, mountains produce ore, fields produce grain, and pastures produce wool.</p>\r\n<p>We use these resources to expand across Catan: we build roads and new settlements, or we upgrade our existing settlements to cities. For example, a road costs 1 brick and 1 lumber. If we do not have the necessary resources, we can acquire them by trading with our opponents.</p>\r\n<p>Each settlement is worth 1 victory point and each city is worth 2 victory points. If you expand cleverly, you may be the first player to reach 10 victory points and thus win the game!</p>",
    commentary:
      "<p>Fun fact: The largest game of Catan was held at Germany's 2015 Spiel convention with 1,040 participants, including its creator Klaus Teuber.</p>",
    faq: "",
    thumb_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559258096678-51Eiofu9mqL.jpg",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559258096678-51Eiofu9mqL.jpg",
    matches_specs: null,
    specs: [],
    mechanics: [
      {
        id: "R0bGq4cAl4",
        url: "https://www.boardgameatlas.com/mechanic/R0bGq4cAl4/undefined",
      },
      {
        id: "ohABM4GjbC",
        url: "https://www.boardgameatlas.com/mechanic/ohABM4GjbC/undefined",
      },
      {
        id: "AVY6EvSQTP",
        url: "https://www.boardgameatlas.com/mechanic/AVY6EvSQTP/undefined",
      },
    ],
    categories: [
      {
        id: "mavSOM8vjH",
        url: "https://www.boardgameatlas.com/category/mavSOM8vjH/undefined",
      },
      {
        id: "N0TkEGfEsF",
        url: "https://www.boardgameatlas.com/category/N0TkEGfEsF/undefined",
      },
      {
        id: "7rV11PKqME",
        url: "https://www.boardgameatlas.com/category/7rV11PKqME/undefined",
      },
      {
        id: "jZEDOpx07e",
        url: "https://www.boardgameatlas.com/category/jZEDOpx07e/undefined",
      },
    ],
    publishers: [
      {
        id: "RY4XltbNAz",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/RY4XltbNAz/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "r2R8bUHIRD",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/r2R8bUHIRD/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "9GlpSO4zcy",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/9GlpSO4zcy/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "yLh8H5FK65",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/yLh8H5FK65/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "0bvxqCgoSm",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/0bvxqCgoSm/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "FG63HUGsWf",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/FG63HUGsWf/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "rK95BcOECc",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/rK95BcOECc/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "eJue6JPxqV",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/eJue6JPxqV/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "beoSVYQtGP",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/beoSVYQtGP/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "m26fBgcJwz",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/m26fBgcJwz/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "HAkNG813TS",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/HAkNG813TS/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "SXnhc3S9lv",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/SXnhc3S9lv/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "hRyavENXm0",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/hRyavENXm0/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "vJkLBDgn1j",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/vJkLBDgn1j/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "Dtrwc4ldq3",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/Dtrwc4ldq3/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "ja1W0hp62r",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/ja1W0hp62r/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "9XxoqlxAVw",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/9XxoqlxAVw/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "P9ZfBj0BBq",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/P9ZfBj0BBq/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "sOdfXQmRBg",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/sOdfXQmRBg/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "1TaoBxZ3GH",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/1TaoBxZ3GH/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "QZq0yTzciC",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/QZq0yTzciC/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "LhiwjGd2o7",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/LhiwjGd2o7/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "EqSluthV2x",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/EqSluthV2x/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "My6tXSDwGi",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/My6tXSDwGi/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "UMssR9EGlp",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/UMssR9EGlp/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "LeyRDCEgWD",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/LeyRDCEgWD/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "9DlitZqr9J",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/9DlitZqr9J/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "J8pMyONAQy",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/J8pMyONAQy/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "8NZhpDk9gP",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/8NZhpDk9gP/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "7GTti1NuCH",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/7GTti1NuCH/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "w9rkA29mT0",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/w9rkA29mT0/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "32liHCLQDl",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/32liHCLQDl/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "DGzIGrGHoR",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/DGzIGrGHoR/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "eQb3IOfYYF",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/eQb3IOfYYF/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "69FdScTBpp",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/69FdScTBpp/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "F8XIZ06AV1",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/F8XIZ06AV1/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "RlZVJC3kRi",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/RlZVJC3kRi/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    designers: [
      {
        id: "LCjyh7WnHd",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/designer/LCjyh7WnHd/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    primary_publisher: {
      id: "RY4XltbNAz",
      name: "KOSMOS",
      url: "https://www.boardgameatlas.com/publisher/RY4XltbNAz/kosmos",
    },
    primary_designer: {
      id: "LCjyh7WnHd",
      name: "Klaus Teuber",
      url: "https://www.boardgameatlas.com/designer/LCjyh7WnHd/klaus-teuber",
    },
    developers: [],
    related_to: [],
    artists: [
      "Volkan Baga",
      "Tanja Donner",
      "Pete Fenlon",
      "Jason Hawkins",
      "Michaela Kienle",
      "Harald Lieske",
      "Michael Menzel",
      "Marion Pott",
      "Matt Schwabel",
      "Franz Vohwinkel",
      "Stephen Graham Walsh",
    ],
    names: [],
    rules_url: "https://www.catan.com/game/catan#prof-easy",
    amazon_rank: 133,
    official_url:
      "https://www.catan.com/?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
    comment_count: 0,
    num_user_ratings: 757,
    average_user_rating: 3.2439652717066156,
    weight_amount: 2,
    weight_units: "lbs ",
    size_height: 11.6,
    size_depth: 3,
    size_units: "inches ",
    historical_low_prices: [
      {
        country: "AU",
        date: "2021-04-07T16:12:05.628Z",
        price: 59.95,
        isLow: true,
      },
      {
        country: "US",
        date: "2021-04-30T00:51:39.784Z",
        price: 44.1,
        isLow: false,
      },
      {
        country: "UK",
        date: "2021-04-30T11:32:52.149Z",
        price: 28.98,
        isLow: true,
      },
    ],
    active: true,
    bgg_id: 13,
    num_user_complexity_votes: 9,
    average_learning_complexity: 2.111111111111111,
    average_strategy_complexity: 2.5555555555555554,
    visits: 3481,
    lists: 1433,
    mentions: 102,
    links: 24,
    plays: 3899,
    rank: 21,
    type: "game",
    sku: "CNS3071",
    upc: "029877030712",
    num_distributors: 1,
    trending_rank: 0,
    listing_clicks: 12,
    is_historical_low: false,
    msrp_text: "$55.00",
    price_text: "$44.10",
    tags: [
      "Die Siedler von Catan ",
      "Les Colons de Catane",
      "Catan (Колонизаторы)",
      "Catan: Das Spiel",
      "Catan: Die Bordspel",
      "Catan: El Juego",
      "Catan: Gra planszowa",
      "Catan: Il Gioco",
      "Catan: Landnemarnir",
      "Catan: O Jogo",
      "Catan: Osnovna igra",
      "Catan: Telepesei",
      "Catane",
      "Catanin Uudisasukkaat",
      "I Coloni di Catan",
      "I Coloni di Katan",
      "Coloniștii din Catan",
      "Colonizadores de Catan",
      "Los Colonos de Catán",
      "Les Colons de Katane",
      "Os Descobridores de Catan",
      "Los Descubridores de Catán",
      "Els Colons de Catan",
      "Katan",
      "Katan no Kaitakusya",
      "Katanas ieceïotâji",
      "Katanas Ieceļotāji",
      "Katani Asustajad",
      "Katano salos naujakuriai",
      "Katano Salos Naujakuriai",
      "De Kolonisten van Catan",
      "Naseljenci otoka Catan",
      "Naseljenici ostrva Katan",
      "Naseljenici ostrva Katan / Насељеници острва Катан",
      "Die Ontdekkers van Catan",
      "Osadníci z Katanu",
      "Osadnicy z Catanu",
      "Settlers fra Catan",
      "The Settlers fra Catan",
      "Settlers från Catan",
      "The Settlers från Catan",
      "The Settlers of Catan",
      "Οι Άποικοι του Κατάν",
      "Заселниците на Катан",
      "Колонизаторы",
      "המתיישבים של קטאן",
      "นักบุกเบิกแห่ง Catan",
      "カタンの開拓者",
      "カタンの開拓者たち",
      "カタンの開拓者たち スタンダード版",
      "卡坦岛",
      "카탄",
      "카탄의 개척자",
      "Catan",
      "Catan 2015 Refresh Base Game",
      "Catan 2015 Refresh",
      "Settlers of Catan The Revised Edition",
      "Settlers of Catan The Printing",
      "Settlers of Catan Collection 2 Base Game 2 Expansions and 3 Extensions",
    ],
    images: {
      thumb:
        "https://d2k4q26owzy373.cloudfront.net/40x40/games/uploaded/1559258096678-51Eiofu9mqL.jpg",
      small:
        "https://d2k4q26owzy373.cloudfront.net/150x150/games/uploaded/1559258096678-51Eiofu9mqL.jpg",
      medium:
        "https://d2k4q26owzy373.cloudfront.net/350x350/games/uploaded/1559258096678-51Eiofu9mqL.jpg",
      large:
        "https://d2k4q26owzy373.cloudfront.net/700x700/games/uploaded/1559258096678-51Eiofu9mqL.jpg",
      original:
        "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559258096678-51Eiofu9mqL.jpg",
    },
    description_preview:
      " The women and men of your expedition build the first two settlements. Fortunately, the land is rich in natural resources. You build roads and new settlements that eventually become cities. Will you succeed in gaining supremacy on Catan? Barter trade dominates the scene. Some resources you have in abundance, other resources are scarce. Ore for wool, brick for lumber - you trade according to what is needed for your current building projects. Proceed strategically! If you found your settlements in the right places and skillfully trade your resources, then the odds will be in your favor. But your opponents are smart too. \r\n To begin the game, we build the game board using hexagonal terrain tiles. Catan is born - a beautiful island with mountains, pastures, hills, fields, and forests, surrounded by the sea. \r\n Each of us places two small houses on spaces where three terrain hexes meet. They are our starting settlements. \r\n And so it begins. I roll two dice. An “11”! Each terrain hex is marked with a die roll number. Each player who owns a settlement adjacent to a terrain hex marked with the number rolled receives a resource produced by this hex. Hills produce brick, forests produce lumber, mountains produce ore, fields produce grain, and pastures produce wool. \r\n We use these resources to expand across Catan: we build roads and new settlements, or we upgrade our existing settlements to cities. For example, a road costs 1 brick and 1 lumber. If we do not have the necessary resources, we can acquire them by trading with our opponents. \r\n Each settlement is worth 1 victory point and each city is worth 2 victory points. If you expand cleverly, you may be the first player to reach 10 victory points and thus win the game! ",
  },
  {
    id: "GP7Y2xOUzj",
    handle: "codenames",
    url: "https://www.boardgameatlas.com/game/GP7Y2xOUzj/codenames",
    name: "Codenames",
    price: "13.49",
    price_ca: "16.80",
    price_uk: "11.39",
    price_au: "24.99",
    msrp: 19.95,
    msrps: [
      {
        country: "US",
        price: 19.95,
      },
      {
        country: "CA",
        price: 0,
      },
      {
        country: "UK",
        price: 0,
      },
      {
        country: "AU",
        price: 0,
      },
    ],
    discount: "0.32",
    year_published: 2015,
    min_players: 2,
    max_players: 8,
    min_playtime: 15,
    max_playtime: 15,
    min_age: 10,
    description:
      "<p>The two rival spymasters know the secret identities of 25 agents. Their teammates know the agents only by their CODENAMES.<br /><br />The teams compete to see who can make contact with all of their agents first. Spymasters give one-word clues that can point to multiple words on the board. Their teammates try to guess words of the right color while avoiding those that belong to the opposing team. And everyone wants to avoid the assassin.<br /><br />Codenames: win or lose, it's fun to figure out the clues.</p>",
    commentary: "",
    faq:
      '<h4>Frequently Asked Questions</h4>\r\n<p><strong>How do you eplain this game?</strong></p>\r\n<p>This is a word-guessing game where two opposing teams compete to get in contact with all of their secret agents first by discovering their codenames. Each team has an assigned Spymaster who possesses a key card that reveals the location of all of the team\'s agents, and they must give a one word clue to help the team discover their agents. Take a risk by offering a clue that will point to as many of the secret agents, but you may unintentionally alert the assassin instead. (Here are the <a href="https://czechgames.com/files/rules/codenames-rules-en.pdf">official rules in PDF</a>.)</p>\r\n<p><strong>What is the best version to buy?</strong></p>\r\n<p>The soaring popularity of Codenames spawned more than 11 different versions to choose from including Marvel, Harry Potter, Disney, and more. If you\'re looking for the best version that will strike a chord with the most diverse set of crowds, start with the original Codenames. If you\'re looking for a solid 2-player cooperative experience, get <a class="game-preview" href="/game/9e0nNBNyOU/codenames-duet" data-tipped-options="ajax: {data: { ids: \'9e0nNBNyOU\', client_id: \'W0AQGbjlZE\' }}">Codenames: Duet</a>.</p>\r\n<p><strong>How can I play online with my friends?</strong></p>\r\n<p><a href="https://codenames.game/">Codenames Online</a> is the official free-to-play digital adaptation of the board game. Create a room, send the invite link, and catch up with friends and families by playing a fun board game alongside your usual Zoom meetings.</p>\r\n<p><strong>Can you play with 2 players?</strong></p>\r\n<p>The official rules include a 2-player variant to allow cooperative play against a simulated opponent. You can try this out even with a large group if they\'re not in the mood for competitive play. If you\'re looking for a strictly 2-player game, then I\'d recommend <a class="game-preview" href="/game/9e0nNBNyOU/codenames-duet" data-tipped-options="ajax: {data: { ids: \'9e0nNBNyOU\', client_id: \'W0AQGbjlZE\' }}">Codenames: Duet</a>, which was specifically designed for a low player count.</p>\r\n<p><strong>How many guesses do you get every turn?</strong></p>\r\n<p>In every turn, the spymaster will say a one-word clue and a number, which tells the team how many codenames are associated with the clue. The team is allowed as many guesses as that number plus one extra. Taking this risk is a big part of the fun!</p>',
    thumb_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254183526-51f6ysXCMmL.jpg",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254183526-51f6ysXCMmL.jpg",
    matches_specs: null,
    specs: [],
    mechanics: [
      {
        id: "0ez69aUfuJ",
        url: "https://www.boardgameatlas.com/mechanic/0ez69aUfuJ/undefined",
      },
      {
        id: "GsNGxZFNCK",
        url: "https://www.boardgameatlas.com/mechanic/GsNGxZFNCK/undefined",
      },
      {
        id: "r6yIFvyXDD",
        url: "https://www.boardgameatlas.com/mechanic/r6yIFvyXDD/undefined",
      },
      {
        id: "hmipYN1R1I",
        url: "https://www.boardgameatlas.com/mechanic/hmipYN1R1I/undefined",
      },
      {
        id: "9jnCsVuRat",
        url: "https://www.boardgameatlas.com/mechanic/9jnCsVuRat/undefined",
      },
    ],
    categories: [
      {
        id: "eX8uuNlQkQ",
        url: "https://www.boardgameatlas.com/category/eX8uuNlQkQ/undefined",
      },
      {
        id: "ge8pIhEUGE",
        url: "https://www.boardgameatlas.com/category/ge8pIhEUGE/undefined",
      },
      {
        id: "bCBXJy9qDw",
        url: "https://www.boardgameatlas.com/category/bCBXJy9qDw/undefined",
      },
      {
        id: "7rV11PKqME",
        url: "https://www.boardgameatlas.com/category/7rV11PKqME/undefined",
      },
      {
        id: "X8J7RM6dxX",
        url: "https://www.boardgameatlas.com/category/X8J7RM6dxX/undefined",
      },
      {
        id: "rHvAx4hH2f",
        url: "https://www.boardgameatlas.com/category/rHvAx4hH2f/undefined",
      },
    ],
    publishers: [
      {
        id: "8eHESCflqX",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/8eHESCflqX/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "dGYFmIWLYs",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/dGYFmIWLYs/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    designers: [
      {
        id: "3P2XFNApXh",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/designer/3P2XFNApXh/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    primary_publisher: {
      id: "8eHESCflqX",
      name: "Czech Games Edition",
      url:
        "https://www.boardgameatlas.com/publisher/8eHESCflqX/czech-games-edition",
    },
    primary_designer: {
      id: "3P2XFNApXh",
      name: "Vlaada Chvátil",
      url: "https://www.boardgameatlas.com/designer/3P2XFNApXh/vlaada-chvtil",
    },
    developers: [],
    related_to: [],
    artists: ["Stéphane Gantiez", "Tomáš Kučerovský"],
    names: [],
    rules_url: "https://czechgames.com/files/rules/codenames-rules-en.pdf",
    amazon_rank: 36,
    cs_rating: 4.6,
    official_url:
      "https://czechgames.com/en/codenames/?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
    comment_count: 0,
    num_user_ratings: 746,
    average_user_rating: 3.65883671246649,
    weight_amount: 1.25,
    weight_units: "lbs ",
    size_height: 9,
    size_depth: 2,
    size_units: "inches ",
    historical_low_prices: [
      {
        country: "AU",
        date: "2021-03-10T22:46:25.218Z",
        price: 24.99,
        isLow: false,
      },
      {
        country: "US",
        date: "2021-04-14T19:21:39.993Z",
        price: 13.49,
        isLow: false,
      },
      {
        country: "UK",
        date: "2021-04-23T05:26:29.202Z",
        price: 11.39,
        isLow: false,
      },
      {
        country: "CA",
        date: "2021-04-25T11:49:00.835Z",
        price: 16.8,
        isLow: false,
      },
    ],
    active: true,
    bgg_id: 178900,
    num_user_complexity_votes: 8,
    average_learning_complexity: 1,
    average_strategy_complexity: 2.125,
    visits: 2449,
    lists: 1519,
    mentions: 76,
    links: 18,
    plays: 8715,
    rank: 11,
    type: "game",
    sku: "CGE00046",
    upc: "8594156310462",
    num_distributors: 1,
    trending_rank: 0,
    listing_clicks: 0,
    is_historical_low: false,
    msrp_text: "$19.95",
    price_text: "$13.49",
    tags: [
      "שם-קוד ",
      "Codenames XXL",
      "Codenames Afrikaans",
      "Codenames Arabic: رسائل سرية",
      "Codenames Edisi Indonesia",
      "Codi secret",
      "Código secreto",
      "Codinomes",
      "Fedőnevek",
      "Krycí jména",
      "Krycie mená",
      "Nome in Codice",
      "Nume de Cod",
      "Tajniacy",
      "Κωδική Ονομασία",
      "Кодові імена: гра слів",
      "Кодови имена",
      "Кодовые Имена",
      "שם-קוד",
      "الأسماء الحركية",
      "コードネーム",
      "機密代號",
      "機密代號: 廣東話版",
      "行动代号",
      "코드네임",
      "Codenames FR",
      "Codenames",
      "Codenames XXL Dutch Edition",
      "Codenames XXL Last Chance",
    ],
    images: {
      thumb:
        "https://d2k4q26owzy373.cloudfront.net/40x40/games/uploaded/1559254183526-51f6ysXCMmL.jpg",
      small:
        "https://d2k4q26owzy373.cloudfront.net/150x150/games/uploaded/1559254183526-51f6ysXCMmL.jpg",
      medium:
        "https://d2k4q26owzy373.cloudfront.net/350x350/games/uploaded/1559254183526-51f6ysXCMmL.jpg",
      large:
        "https://d2k4q26owzy373.cloudfront.net/700x700/games/uploaded/1559254183526-51f6ysXCMmL.jpg",
      original:
        "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254183526-51f6ysXCMmL.jpg",
    },
    description_preview:
      " The two rival spymasters know the secret identities of 25 agents. Their teammates know the agents only by their CODENAMES.  The teams compete to see who can make contact with all of their agents first. Spymasters give one-word clues that can point to multiple words on the board. Their teammates try to guess words of the right color while avoiding those that belong to the opposing team. And everyone wants to avoid the assassin.  Codenames: win or lose, it's fun to figure out the clues. ",
  },
  {
    id: "OF145SrX44",
    handle: "7-wonders",
    url: "https://www.boardgameatlas.com/game/OF145SrX44/7-wonders",
    name: "7 Wonders",
    price: "44.95",
    price_ca: "64.95",
    price_uk: "0.00",
    price_au: "0.00",
    msrp: 49.99,
    msrps: [
      {
        country: "UK",
        price: 42.99,
      },
      {
        country: "US",
        price: 49.99,
      },
    ],
    discount: "0.10",
    year_published: 2010,
    min_players: 2,
    max_players: 7,
    min_playtime: 30,
    max_playtime: 45,
    min_age: 10,
    description:
      "<p>You are the leader of one of the 7 great cities of the Ancient World. Gather resources, develop commercial routes and affirm your military supremacy. Build your city and erect an architectural wonder which will transcend future times!<br /><br /><strong> 7 Wonders</strong> is a simple and addictive game for the whole family. In 30 minutes you can raise a complete civilization and build the greatest Wonders of the World.</p>\r\n<p><em>Winner of the 2011 Kennerspiel des Jahres (Enthusiasts Game of the Year) Award.</em></p>",
    commentary: "",
    faq: "",
    thumb_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559253945470-61dlm9QcXpL.jpg",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559253945470-61dlm9QcXpL.jpg",
    matches_specs: null,
    specs: [],
    mechanics: [
      {
        id: "wV5peB05xs",
        url: "https://www.boardgameatlas.com/mechanic/wV5peB05xs/undefined",
      },
      {
        id: "WPytek5P8l",
        url: "https://www.boardgameatlas.com/mechanic/WPytek5P8l/undefined",
      },
      {
        id: "lA3KUtVFCy",
        url: "https://www.boardgameatlas.com/mechanic/lA3KUtVFCy/undefined",
      },
      {
        id: "u9IJEE1QBN",
        url: "https://www.boardgameatlas.com/mechanic/u9IJEE1QBN/undefined",
      },
    ],
    categories: [
      {
        id: "a8NM5cugJX",
        url: "https://www.boardgameatlas.com/category/a8NM5cugJX/undefined",
      },
      {
        id: "eX8uuNlQkQ",
        url: "https://www.boardgameatlas.com/category/eX8uuNlQkQ/undefined",
      },
      {
        id: "ODWOjWAJj3",
        url: "https://www.boardgameatlas.com/category/ODWOjWAJj3/undefined",
      },
    ],
    publishers: [
      {
        id: "aHjtFBSGhK",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/aHjtFBSGhK/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "EzK672818k",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/EzK672818k/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "1LE7oe5KVZ",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/1LE7oe5KVZ/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "nXkH65MZyn",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/nXkH65MZyn/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "Fn8zCUvgwd",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/Fn8zCUvgwd/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "iCcEfKxF09",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/iCcEfKxF09/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "b33BrKkCsN",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/b33BrKkCsN/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "UMssR9EGlp",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/UMssR9EGlp/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "J8pMyONAQy",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/J8pMyONAQy/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "mS7cBdlVnm",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/mS7cBdlVnm/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "3USxqN1uFW",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/3USxqN1uFW/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "gtEJZ3LsMl",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/gtEJZ3LsMl/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    designers: [
      {
        id: "jeBRjPzECh",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/designer/jeBRjPzECh/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    primary_publisher: {
      id: "aHjtFBSGhK",
      name: "Repos Production",
      url:
        "https://www.boardgameatlas.com/publisher/aHjtFBSGhK/repos-production",
    },
    primary_designer: {
      id: "jeBRjPzECh",
      name: "Antoine Bauza",
      url: "https://www.boardgameatlas.com/designer/jeBRjPzECh/antoine-bauza",
    },
    developers: [],
    related_to: [],
    artists: ["Antoine Bauza", "Miguel Coimbra"],
    names: [],
    rules_url:
      "http://www.7wonders.net/wp-content/uploads/2017/06/7WONDERS_RULES_US.pdf",
    amazon_rank: 3784,
    cs_rating: 4.4,
    official_url:
      "http://www.7wonders.net/7-wonders/?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
    comment_count: 0,
    num_user_ratings: 739,
    average_user_rating: 3.692006572588441,
    weight_amount: 2.65,
    weight_units: "lbs",
    size_height: 11.26,
    size_depth: 3.15,
    size_units: "inches ",
    historical_low_prices: [
      {
        country: "AU",
        date: "2021-02-16T23:28:44.202Z",
        price: 63.99,
        isLow: false,
      },
      {
        country: "UK",
        date: "2021-03-10T04:42:55.427Z",
        price: 29.29,
        isLow: false,
      },
      {
        country: "CA",
        date: "2021-04-03T10:24:12.220Z",
        price: 64.95,
        isLow: false,
      },
      {
        country: "US",
        date: "2021-04-14T16:58:47.656Z",
        price: 44.95,
        isLow: false,
      },
    ],
    active: true,
    bgg_id: 68448,
    num_user_complexity_votes: 9,
    average_learning_complexity: 2.7777777777777777,
    average_strategy_complexity: 2.5555555555555554,
    visits: 2716,
    lists: 1446,
    mentions: 90,
    links: 14,
    plays: 6919,
    rank: 10,
    type: "game",
    sku: "ASMSV02",
    upc: "5425016924334",
    num_distributors: 1,
    trending_rank: 0,
    listing_clicks: 16,
    is_historical_low: false,
    msrp_text: "$49.99",
    price_text: "$44.95",
    tags: [
      "7 csoda",
      "7 Cudów Świata",
      "7 divů světa",
      "7 чудес",
      "7 สิ่งมหัศจรรย์",
      "7원더스",
      "Τα 7 θαύματα του κόσμου",
      "七大奇蹟",
      "世界の七不思議",
      "7 Wonders Edition",
      "7 Wonders",
      "7 Wonders Collection 1 Base Game Leaders Cities",
      "7 Wonders Core Base Set",
    ],
    images: {
      thumb:
        "https://d2k4q26owzy373.cloudfront.net/40x40/games/uploaded/1559253945470-61dlm9QcXpL.jpg",
      small:
        "https://d2k4q26owzy373.cloudfront.net/150x150/games/uploaded/1559253945470-61dlm9QcXpL.jpg",
      medium:
        "https://d2k4q26owzy373.cloudfront.net/350x350/games/uploaded/1559253945470-61dlm9QcXpL.jpg",
      large:
        "https://d2k4q26owzy373.cloudfront.net/700x700/games/uploaded/1559253945470-61dlm9QcXpL.jpg",
      original:
        "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559253945470-61dlm9QcXpL.jpg",
    },
    description_preview:
      " You are the leader of one of the 7 great cities of the Ancient World. Gather resources, develop commercial routes and affirm your military supremacy. Build your city and erect an architectural wonder which will transcend future times!    7 Wonders  is a simple and addictive game for the whole family. In 30 minutes you can raise a complete civilization and build the greatest Wonders of the World. \r\n  Winner of the 2011 Kennerspiel des Jahres (Enthusiasts Game of the Year) Award.  ",
  },
  {
    id: "AuBvbISHR6",
    handle: "ticket-to-ride",
    url: "https://www.boardgameatlas.com/game/AuBvbISHR6/ticket-to-ride",
    name: "Ticket To Ride",
    price: "39.69",
    price_ca: "49.95",
    price_uk: "24.99",
    price_au: "62.95",
    msrp: 49.99,
    msrps: [
      {
        country: "UK",
        price: 39.99,
      },
      {
        country: "US",
        price: 49.99,
      },
    ],
    discount: "0.21",
    year_published: 2004,
    min_players: 2,
    max_players: 5,
    min_playtime: 45,
    max_playtime: 90,
    min_age: 8,
    description:
      "Ticket to Ride is a cross-country train adventure game. Players collect train cards that enable them to claim railway routes connecting cities throughout North America. The longer the routes, the more points they earn. Additional points come to those who can fulfill their Destination Tickets by connecting two distant cities, and to the player who builds the longest continuous railway. So climb aboard for some railroading fun and adventure. You've got a Ticket to Ride!<br />\r\n<br />\r\nOctober 2, 1900 -- it's 28 years to the day that noted London eccentric, Phileas Fogg accepted and then won a 20,000 bet that he could travel Around the World in 80 Days. Now at the dawn of the century some old friends have gathered to celebrate Fogg's impetuous and lucrative gamble -- and to propose a new wager of their own. The stakes: $1 million in a winner-takes-all competition. The objective: to see the most cities in North America -- in just 7 days. <br />\r\n<br />\r\n-Spiel Des Jahres 2004(German game of the year)<br />\r\n-As d'Or Cannes 2004 (French game of the year)<br />\r\n-Game of the year 2004 - Japan<br />\r\n-Game of the year 2004 - Sweden<br />\r\n-Game of the year 2004 - Finland<br />\r\n-Diana Jones Excellence in Gaming Award 2004<br />\r\n-Origins Award Winner - Best Board Game 2005<br />\r\n-Game of the year 2004 - Spain<br />\r\n-Parent's Choice Foundation Silver Medal 2004",
    commentary: "",
    faq: "",
    thumb_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254202421-61wLscAHHSL.jpg",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254202421-61wLscAHHSL.jpg",
    matches_specs: null,
    specs: [],
    mechanics: [
      {
        id: "wV5peB05xs",
        url: "https://www.boardgameatlas.com/mechanic/wV5peB05xs/undefined",
      },
      {
        id: "WPytek5P8l",
        url: "https://www.boardgameatlas.com/mechanic/WPytek5P8l/undefined",
      },
      {
        id: "lA3KUtVFCy",
        url: "https://www.boardgameatlas.com/mechanic/lA3KUtVFCy/undefined",
      },
      {
        id: "ohABM4GjbC",
        url: "https://www.boardgameatlas.com/mechanic/ohABM4GjbC/undefined",
      },
    ],
    categories: [
      {
        id: "h8wfZG0j3I",
        url: "https://www.boardgameatlas.com/category/h8wfZG0j3I/undefined",
      },
      {
        id: "JwHcKqxh33",
        url: "https://www.boardgameatlas.com/category/JwHcKqxh33/undefined",
      },
    ],
    publishers: [
      {
        id: "gniNJ5XEjM",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/gniNJ5XEjM/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    designers: [
      {
        id: "yozxd5BrMc",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/designer/yozxd5BrMc/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    primary_publisher: {
      name: "Days of Wonder",
      id: "gniNJ5XEjM",
      url: "https://www.boardgameatlas.com/publisher/gniNJ5XEjM/days-of-wonder",
    },
    primary_designer: {
      name: "Alan R. Moon",
      id: "yozxd5BrMc",
      url: "https://www.boardgameatlas.com/designer/yozxd5BrMc/alan-r-moon",
    },
    developers: [],
    related_to: [],
    artists: ["Julien Delval", "Cyrille Daujean"],
    names: [],
    rules_url:
      "https://ncdn0.daysofwonder.com/tickettoride/en/img/tt_rules_2015_en.pdf",
    amazon_rank: 338,
    cs_rating: 4.5,
    official_url:
      "https://www.daysofwonder.com/tickettoride/en/?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
    comment_count: 0,
    num_user_ratings: 660,
    average_user_rating: 3.5568778897817475,
    weight_amount: 2.8,
    weight_units: "lbs ",
    size_height: 11.8,
    size_depth: 3,
    size_units: "inches ",
    historical_low_prices: [
      {
        country: "AU",
        date: "2021-04-07T17:29:18.478Z",
        price: 62.95,
        isLow: true,
      },
      {
        country: "UK",
        date: "2021-04-15T04:06:43.412Z",
        price: 24.99,
        isLow: false,
      },
      {
        country: "CA",
        date: "2021-04-20T12:05:19.785Z",
        price: 49.95,
        isLow: false,
      },
      {
        country: "US",
        date: "2021-04-30T09:08:14.834Z",
        price: 39.69,
        isLow: false,
      },
    ],
    active: true,
    bgg_id: 9209,
    num_user_complexity_votes: 6,
    average_learning_complexity: 2,
    average_strategy_complexity: 2.3333333333333335,
    visits: 3185,
    lists: 1172,
    mentions: 59,
    links: 15,
    plays: 5146,
    rank: 16,
    type: "game",
    sku: "DOW7201",
    upc: "824968717912",
    num_distributors: 1,
    trending_rank: 0,
    listing_clicks: 0,
    is_historical_low: false,
    msrp_text: "$49.99",
    price_text: "$39.69",
    tags: [
      "Ticket to Ride",
      "Zug um Zug (German)",
      " Les Aventuriers du Rail (French)",
      "Aventureros al Tren (Spanish)",
      "Wsiąść do pociągu (Polish)",
      "Menolippu (Finnish)",
      "Ticket To Ride - Ding & Dent",
      "Ticket To Ride 1 Anniversary Edition",
      "Ticket To Ride: 15th Anniversary Edition",
      "Ticket To Ride: 15th Anniversary Special Edition",
      "Ticket to Ride: 15th Anniversary Edition - Ding/Dent",
    ],
    images: {
      thumb:
        "https://d2k4q26owzy373.cloudfront.net/40x40/games/uploaded/1559254202421-61wLscAHHSL.jpg",
      small:
        "https://d2k4q26owzy373.cloudfront.net/150x150/games/uploaded/1559254202421-61wLscAHHSL.jpg",
      medium:
        "https://d2k4q26owzy373.cloudfront.net/350x350/games/uploaded/1559254202421-61wLscAHHSL.jpg",
      large:
        "https://d2k4q26owzy373.cloudfront.net/700x700/games/uploaded/1559254202421-61wLscAHHSL.jpg",
      original:
        "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254202421-61wLscAHHSL.jpg",
    },
    description_preview:
      "Ticket to Ride is a cross-country train adventure game. Players collect train cards that enable them to claim railway routes connecting cities throughout North America. The longer the routes, the more points they earn. Additional points come to those who can fulfill their Destination Tickets by connecting two distant cities, and to the player who builds the longest continuous railway. So climb aboard for some railroading fun and adventure. You've got a Ticket to Ride! \r\n \r\nOctober 2, 1900 -- it's 28 years to the day that noted London eccentric, Phileas Fogg accepted and then won a 20,000 bet that he could travel Around the World in 80 Days. Now at the dawn of the century some old friends have gathered to celebrate Fogg's impetuous and lucrative gamble -- and to propose a new wager of their own. The stakes: $1 million in a winner-takes-all competition. The objective: to see the most cities in North America -- in just 7 days.  \r\n \r\n-Spiel Des Jahres 2004(German game of the year) \r\n-As d'Or Cannes 2004 (French game of the year) \r\n-Game of the year 2004 - Japan \r\n-Game of the year 2004 - Sweden \r\n-Game of the year 2004 - Finland \r\n-Diana Jones Excellence in Gaming Award 2004 \r\n-Origins Award Winner - Best Board Game 2005 \r\n-Game of the year 2004 - Spain \r\n-Parent's Choice Foundation Silver Medal 2004",
  },
  {
    id: "yqR4PtpO8X",
    handle: "scythe",
    url: "https://www.boardgameatlas.com/game/yqR4PtpO8X/scythe",
    name: "Scythe",
    price: "56.30",
    price_ca: "75.83",
    price_uk: "56.95",
    price_au: "118.95",
    msrp: 90,
    msrps: [
      {
        country: "UK",
        price: 67,
      },
      {
        country: "US",
        price: 90,
      },
    ],
    discount: "0.37",
    year_published: 2016,
    min_players: 1,
    max_players: 5,
    min_playtime: 90,
    max_playtime: 120,
    min_age: 14,
    description:
      "<p><em>Scythe</em> gives players almost complete control over their fate. Other than each player's individual hidden objective card, the only elements of luck or variability are &quot;Encounter&quot; cards that players will draw as they interact with the citizens of newly explored lands. Each encounter card provides the player with several options, allowing them to mitigate the luck of the draw through their selection. Combat is also driven by choices, not luck or randomness.<br /><br /><em>Scythe</em> uses a streamlined action-selection mechanism (no rounds or phases) to keep gameplay moving at a brisk pace and reduce downtime between turns. While there is plenty of direct conflict for players who seek it, there is no player elimination.<br /><br />Every part of <em>Scythe</em> has an aspect of engine-building to it. Players can upgrade actions to become more efficient, build structures that improve their position on the map, enlist new recruits to enhance character abilities, activate mechs to deter opponents from invading, and expand their borders to reap greater types and quantities of resources. These engine-building aspects create a sense of momentum and progress throughout the game. The order in which players improve their engine adds to the unique feel of each game, even when playing one faction multiple times.</p>",
    commentary: "",
    faq: "",
    thumb_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254971843-513-lrmjs2L.jpg",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254971843-513-lrmjs2L.jpg",
    matches_specs: null,
    specs: [],
    mechanics: [
      {
        id: "Bc7R8pLoGk",
        url: "https://www.boardgameatlas.com/mechanic/Bc7R8pLoGk/undefined",
      },
      {
        id: "05zCZoLvQJ",
        url: "https://www.boardgameatlas.com/mechanic/05zCZoLvQJ/undefined",
      },
      {
        id: "yu3eas6v7A",
        url: "https://www.boardgameatlas.com/mechanic/yu3eas6v7A/undefined",
      },
      {
        id: "qu5BcGjAzk",
        url: "https://www.boardgameatlas.com/mechanic/qu5BcGjAzk/undefined",
      },
      {
        id: "BeD8NYAaSU",
        url: "https://www.boardgameatlas.com/mechanic/BeD8NYAaSU/undefined",
      },
      {
        id: "dITGE93SCS",
        url: "https://www.boardgameatlas.com/mechanic/dITGE93SCS/undefined",
      },
      {
        id: "XM2FYZmBHH",
        url: "https://www.boardgameatlas.com/mechanic/XM2FYZmBHH/undefined",
      },
      {
        id: "fBOTEBUAmV",
        url: "https://www.boardgameatlas.com/mechanic/fBOTEBUAmV/undefined",
      },
    ],
    categories: [
      {
        id: "85OKv8p5Ow",
        url: "https://www.boardgameatlas.com/category/85OKv8p5Ow/undefined",
      },
      {
        id: "nWDac9tQzt",
        url: "https://www.boardgameatlas.com/category/nWDac9tQzt/undefined",
      },
      {
        id: "Bq6M0TJyg7",
        url: "https://www.boardgameatlas.com/category/Bq6M0TJyg7/undefined",
      },
      {
        id: "zyj9ZK3mHB",
        url: "https://www.boardgameatlas.com/category/zyj9ZK3mHB/undefined",
      },
      {
        id: "3B3QpKvXD3",
        url: "https://www.boardgameatlas.com/category/3B3QpKvXD3/undefined",
      },
      {
        id: "4hZlqoitAY",
        url: "https://www.boardgameatlas.com/category/4hZlqoitAY/undefined",
      },
      {
        id: "buDTYyPw4D",
        url: "https://www.boardgameatlas.com/category/buDTYyPw4D/undefined",
      },
    ],
    publishers: [
      {
        id: "njVFVNfJc7",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/njVFVNfJc7/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "9GlpSO4zcy",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/9GlpSO4zcy/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "tm3Gi5QR8G",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/tm3Gi5QR8G/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "mGVCPaJvDN",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/mGVCPaJvDN/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "hPX4pYxYZb",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/hPX4pYxYZb/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "uUXTHHVIcL",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/uUXTHHVIcL/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "BhORjPosne",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/BhORjPosne/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "I1WhPogSKu",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/I1WhPogSKu/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "mFJ3imEWZT",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/mFJ3imEWZT/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "mky4EQg5fZ",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/mky4EQg5fZ/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "uufXqkA7bx",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/uufXqkA7bx/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "FQD3Hj0ZEg",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/FQD3Hj0ZEg/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "Nz4vpToxr1",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/Nz4vpToxr1/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "HJeBOioKze",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/HJeBOioKze/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "yB7ysL3OCY",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/yB7ysL3OCY/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "d0r9CeP7E6",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/d0r9CeP7E6/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "LyhMeYJbHu",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/LyhMeYJbHu/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    designers: [
      {
        id: "QIz5pAPzFk",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/designer/QIz5pAPzFk/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    primary_publisher: {
      id: "njVFVNfJc7",
      name: "Stonemaier Games",
      url:
        "https://www.boardgameatlas.com/publisher/njVFVNfJc7/stonemaier-games",
    },
    primary_designer: {
      id: "QIz5pAPzFk",
      name: "Jamey Stegmaier",
      url: "https://www.boardgameatlas.com/designer/QIz5pAPzFk/jamey-stegmaier",
    },
    developers: [],
    related_to: [],
    artists: ["Jakub Różalski"],
    names: [],
    rules_url: "https://app.box.com/s/rj3jrw0rab2uiz02up89kbant5g8ew1p",
    amazon_rank: 1583,
    cs_rating: 4.7,
    official_url:
      "https://stonemaiergames.com/games/scythe/?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
    comment_count: 0,
    num_user_ratings: 658,
    average_user_rating: 4.071036848640326,
    weight_amount: 7.3,
    weight_units: "lbs",
    size_height: 14.4,
    size_depth: 3.9,
    size_units: "inches ",
    historical_low_prices: [
      {
        country: "CA",
        date: "2021-04-06T22:58:27.313Z",
        price: 75.83,
        isLow: false,
      },
      {
        country: "AU",
        date: "2021-04-07T16:08:47.778Z",
        price: 118.95,
        isLow: true,
      },
      {
        country: "UK",
        date: "2021-04-09T04:16:37.466Z",
        price: 56.95,
        isLow: false,
      },
      {
        country: "US",
        date: "2021-04-26T11:14:54.891Z",
        price: 56.3,
        isLow: false,
      },
    ],
    active: true,
    bgg_id: 169786,
    num_user_complexity_votes: 13,
    average_learning_complexity: 3.1538461538461537,
    average_strategy_complexity: 3.3846153846153846,
    visits: 8901,
    lists: 1772,
    mentions: 375,
    links: 41,
    plays: 4105,
    rank: 2,
    type: "game",
    sku: "STM600",
    upc: "653341025005",
    num_distributors: 1,
    trending_rank: 0,
    listing_clicks: 116,
    is_historical_low: false,
    msrp_text: "$90.00",
    price_text: "$56.30",
    tags: [
      "Sçythe",
      "Серп",
      "大鎌戦役",
      "鐮刀戰爭",
      "사이쓰",
      "Коса",
      "사이드",
      "Scythe",
      "Scythe (Box Damage)",
      "Scythe Collector's Edition",
      "Scythe Special Edition",
      "Scythe Collection 6 Base Game Legendary Box 2 Expansions",
      "Scythe Core Set",
    ],
    images: {
      thumb:
        "https://d2k4q26owzy373.cloudfront.net/40x40/games/uploaded/1559254971843-513-lrmjs2L.jpg",
      small:
        "https://d2k4q26owzy373.cloudfront.net/150x150/games/uploaded/1559254971843-513-lrmjs2L.jpg",
      medium:
        "https://d2k4q26owzy373.cloudfront.net/350x350/games/uploaded/1559254971843-513-lrmjs2L.jpg",
      large:
        "https://d2k4q26owzy373.cloudfront.net/700x700/games/uploaded/1559254971843-513-lrmjs2L.jpg",
      original:
        "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254971843-513-lrmjs2L.jpg",
    },
    description_preview:
      '  Scythe  gives players almost complete control over their fate. Other than each player\'s individual hidden objective card, the only elements of luck or variability are "Encounter" cards that players will draw as they interact with the citizens of newly explored lands. Each encounter card provides the player with several options, allowing them to mitigate the luck of the draw through their selection. Combat is also driven by choices, not luck or randomness.   Scythe  uses a streamlined action-selection mechanism (no rounds or phases) to keep gameplay moving at a brisk pace and reduce downtime between turns. While there is plenty of direct conflict for players who seek it, there is no player elimination.  Every part of  Scythe  has an aspect of engine-building to it. Players can upgrade actions to become more efficient, build structures that improve their position on the map, enlist new recruits to enhance character abilities, activate mechs to deter opponents from invading, and expand their borders to reap greater types and quantities of resources. These engine-building aspects create a sense of momentum and progress throughout the game. The order in which players improve their engine adds to the unique feel of each game, even when playing one faction multiple times. ',
  },
  {
    id: "i5Oqu5VZgP",
    handle: "azul",
    url: "https://www.boardgameatlas.com/game/i5Oqu5VZgP/azul",
    name: "Azul",
    price: "24.99",
    price_ca: "41.95",
    price_uk: "26.09",
    price_au: "49.99",
    msrp: 39.99,
    msrps: [
      {
        country: "UK",
        price: 39.99,
      },
      {
        country: "US",
        price: 39.99,
      },
    ],
    discount: "0.38",
    year_published: 2017,
    min_players: 2,
    max_players: 4,
    min_playtime: 30,
    max_playtime: 60,
    min_age: 8,
    description:
      "<p><strong>Azul</strong> was designed by the world famous, award-winning game author Michael Riesling. Azul captures the beautiful aesthetics of Moorish art in a contemporary board game.</p>\r\n<p>Players compete as artisans decorating the walls of the royal Palace of Dvora. By carefully drafting the correct Quantity and style of tiles, the most clever of artisans plan ahead to maximize the beauty of their work (not to mention their scores!) while ensuring they wasted no supplies in the process.</p>\r\n<p>Introduced by the moors, &quot;azulejos&quot; (originally white and blue ceramic tiles) were fully embraced by the Portuguese, when their King Manuel I, on a visit to the Alhambra Palace in Southern Spain, was mesmerized by the stunning beauty of the Moorish decorative tiles. The King, awestruck by the interior beauty of the Alhambra, immediately ordered that his own Palace in Portugal be decorated with similar wall tiles.</p>\r\n<p>As a tile-laying artist, you have been challenged to embellish the walls of the royal Palace of Dvora.</p>",
    commentary: "",
    faq: "",
    thumb_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254200327-61EFZADvURL.jpg",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254200327-61EFZADvURL.jpg",
    matches_specs: null,
    specs: [],
    mechanics: [
      {
        id: "wV5peB05xs",
        url: "https://www.boardgameatlas.com/mechanic/wV5peB05xs/undefined",
      },
      {
        id: "9ZlbQA8L5l",
        url: "https://www.boardgameatlas.com/mechanic/9ZlbQA8L5l/undefined",
      },
      {
        id: "9YdRn9J9oZ",
        url: "https://www.boardgameatlas.com/mechanic/9YdRn9J9oZ/undefined",
      },
      {
        id: "8PN2HE86wg",
        url: "https://www.boardgameatlas.com/mechanic/8PN2HE86wg/undefined",
      },
    ],
    categories: [
      {
        id: "hBqZ3Ar4RJ",
        url: "https://www.boardgameatlas.com/category/hBqZ3Ar4RJ/undefined",
      },
    ],
    publishers: [
      {
        id: "geGEEdKZJI",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/geGEEdKZJI/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
      {
        id: "TpGyVwxvun",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/publisher/TpGyVwxvun/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    designers: [
      {
        id: "6xWTtWTLId",
        num_games: null,
        score: 9999999,
        game: {},
        url: "https://www.boardgameatlas.com/designer/6xWTtWTLId/undefined",
        images: {
          thumb: null,
          small: null,
          medium: null,
          large: null,
          original: null,
        },
      },
    ],
    primary_publisher: {
      id: "geGEEdKZJI",
      name: "Next Move Games",
      url:
        "https://www.boardgameatlas.com/publisher/geGEEdKZJI/next-move-games",
    },
    primary_designer: {
      id: "6xWTtWTLId",
      name: "Michael Kiesling",
      url:
        "https://www.boardgameatlas.com/designer/6xWTtWTLId/michael-kiesling",
    },
    developers: [],
    related_to: [],
    artists: ["Philippe Guérin", "Chris Quilliams"],
    names: [],
    rules_url:
      "https://www.nextmovegames.com/en/index.php?controller=attachment&id_attachment=9",
    amazon_rank: 985,
    cs_rating: 4.4,
    official_url:
      "https://www.nextmovegames.com/en/home/48-azul.html?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
    comment_count: 1,
    num_user_ratings: 642,
    average_user_rating: 3.853016142735767,
    weight_amount: 2.74,
    weight_units: "lbs",
    size_height: 10,
    size_depth: 2.75,
    size_units: "inches ",
    historical_low_prices: [
      {
        country: "CA",
        date: "2021-02-23T01:14:45.242Z",
        price: 41.95,
        isLow: false,
      },
      {
        country: "AU",
        date: "2021-03-10T18:10:36.696Z",
        price: 49.99,
        isLow: false,
      },
      {
        country: "US",
        date: "2021-04-22T12:10:59.559Z",
        price: 24.99,
        isLow: false,
      },
      {
        country: "UK",
        date: "2021-04-27T03:24:45.089Z",
        price: 26.09,
        isLow: false,
      },
    ],
    active: true,
    bgg_id: 230802,
    num_user_complexity_votes: 11,
    average_learning_complexity: 2.090909090909091,
    average_strategy_complexity: 2.181818181818182,
    visits: 5696,
    lists: 1666,
    mentions: 178,
    links: 23,
    plays: 6901,
    rank: 6,
    type: "game",
    num_distributors: 0,
    trending_rank: 0,
    listing_clicks: 16,
    is_historical_low: false,
    msrp_text: "$39.99",
    price_text: "$24.99",
    tags: [
      "アズール",
      "花磚物語",
      "아줄",
      "Azul Next Move Bundle",
      "Azul Plan B Board Game",
      "Azul ML",
      "Azul Dent Ding",
      "Azul (Box Damage)",
      "Azul",
    ],
    images: {
      thumb:
        "https://d2k4q26owzy373.cloudfront.net/40x40/games/uploaded/1559254200327-61EFZADvURL.jpg",
      small:
        "https://d2k4q26owzy373.cloudfront.net/150x150/games/uploaded/1559254200327-61EFZADvURL.jpg",
      medium:
        "https://d2k4q26owzy373.cloudfront.net/350x350/games/uploaded/1559254200327-61EFZADvURL.jpg",
      large:
        "https://d2k4q26owzy373.cloudfront.net/700x700/games/uploaded/1559254200327-61EFZADvURL.jpg",
      original:
        "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254200327-61EFZADvURL.jpg",
    },
    description_preview:
      '  Azul  was designed by the world famous, award-winning game author Michael Riesling. Azul captures the beautiful aesthetics of Moorish art in a contemporary board game. \r\n Players compete as artisans decorating the walls of the royal Palace of Dvora. By carefully drafting the correct Quantity and style of tiles, the most clever of artisans plan ahead to maximize the beauty of their work (not to mention their scores!) while ensuring they wasted no supplies in the process. \r\n Introduced by the moors, "azulejos" (originally white and blue ceramic tiles) were fully embraced by the Portuguese, when their King Manuel I, on a visit to the Alhambra Palace in Southern Spain, was mesmerized by the stunning beauty of the Moorish decorative tiles. The King, awestruck by the interior beauty of the Alhambra, immediately ordered that his own Palace in Portugal be decorated with similar wall tiles. \r\n As a tile-laying artist, you have been challenged to embellish the walls of the royal Palace of Dvora. ',
  },
];

export default tempData;
